name: Pull-Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Run gradle build
        run:  ./gradlew check --info --stacktrace --console=plain --max-workers=1 --no-daemon --build-cache --scan -s -Dkotlin.colors.enabled=false

